embedding_name: featurenerf
featurenerf_ckpt: ckpts/robo_2d_r18_all/pixel_nerf_latest
embedding_ckpt: none

pixelnerf_mode: global

domain_randomization: False

dataset_root: expert_demonstrations

lr: 1e-3

# num_trajs: 50
num_trajs: 100


log_dir: ???

image_size: 128


batch_size: 32

use_reward_predictor: False

freeze_encoder: True
